deployment:
  tasks:
    - export DEPLOYPATH=/home4/codehous/public_html/
    # Copy entire public directory contents to root
    - /bin/cp -r public/* $DEPLOYPATH
    # Copy other assets
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r favicons $DEPLOYPATH
    # Copy package.json
    - /bin/cp package.json $DEPLOYPATH